export const LOGIN_REQUESTS ="LOGIN_REQUESTS";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";


export const REGISTER_REQUESTS ="REGISTER_REQUESTS";
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";


export const LOAD_REQUESTS ="LOAD_REQUESTS";
export const LOAD_SUCCESS ="LOAD_SUCCESS";
export const LOAD_FAIL="LOAD_FAIL";


export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";


export const UPDATE_PROFILE_REQUESTS ="UPDATE_PROFILE_REQUESTS";
export const UPDATE_PROFILE_SUCCESS ="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET";


export const UPDATE_PASSWORD_REQUESTS ="UPDATE_PASSWORD_REQUESTS";
export const UPDATE_PASSWORD_SUCCESS ="UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_RESET="UPDATE_PASSWORD_RESET";

export const CLEAR_ERRORS ="CLEAR_ERRORS";